### ISSUE TITLE
sqlite3.OperationalError: unable to open database file

### ISSUE THREAD

**Issue by TheQL** [liskin/foursquare-swarm-ical#11]
After I got this error on run I tried to  `pip install pysqlite3` but that failed. Searched around and found some indicators there might a problem with pysqlite on macOS, but not sure. Running macOS 14.7.1 (M2 Pro), python 3.12 via homebrew.

```
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pysqlite3
Failed to build pysqlite3

[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: pip install --upgrade pip
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (pysqlite3)
```

So with this you'd send me to the pysqlite3 guys, I guess... Just wondered if there'd be some kind of workaround as the shutdown date is approaching and I'm not sure API access will work at all after that.

Following this interesting guide https://til.simonwillison.net/sqlite/build-specific-sqlite-pysqlite-macos sadly left me with an x86_64.whl file :(

**Comment by liskin** [comment]
Can you post the full error you're getting with the "unable to open database file"? This project just uses the sqlite module that's built-in to Python, and I'd be super surprised if that didn't work. The issue is likely elsewhere - file permissions or something.

Re api access - I'm not too worried actually. This already uses an api that isn't officially documented and hasn't been for years. Also the docs probably need an update because to get the token one needs to login to Swarm's web app and fish the token out of cookies using the browser DevTools. But then it works and hopefully will until someone decides to break it, but I hope they've forgotten this even exists lol

**Comment by TheQL** [comment]
Thanks for your reply. Ok, I believed it'd be something with pysqlite3 not building properly on Apple Silicon, found a few indications on the web. Was about to try again tomorrow on an older intel Mac.

Nevertheless, if it can somehow be solved otherwise I'd be glad. Wasn't aware there's another sqlite implementation already included with Python.

```
Traceback (most recent call last):
  File "./venvs/foursquare-swarm-ical/bin/./foursquare-swarm-ical", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "./venvs/foursquare-swarm-ical/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./venvs/foursquare-swarm-ical/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "./venvs/foursquare-swarm-ical/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./venvs/foursquare-swarm-ical/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "./venvs/foursquare-swarm-ical/lib/python3.12/site-packages/foursquare_swarm_ical/cli.py", line 78, in cli
    with db.database(database) as db_conn:
         ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "./venvs/foursquare-swarm-ical/lib/python3.12/site-packages/foursquare_swarm_ical/db.py", line 17, in database
    db = sqlite3.connect(filename, isolation_level=None)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file
```

**Comment by liskin** [comment]
Hm, I was hoping the traceback would tell us more but there isn't much really. I still think it's just a file permissions issue or something. Can you perhaps try the `--database` option and give it some other file path? Maybe your Mac setup is weird in some way (I've seen OneDrive completely take over people's home dirs for example).

**Comment by TheQL** [comment]
Pretty sure my permissions are ok, but I did it the "hard" way:

```
(foursquare-swarm-ical) <username>@<computername>:~/venvs/foursquare-swarm-ical/bin # mkdir ~/sqlitedb
(foursquare-swarm-ical) <username>@<computername>:~/venvs/foursquare-swarm-ical/bin # chown <username>: ~/sqlitedb
(foursquare-swarm-ical) <username>@<computername>:~/venvs/foursquare-swarm-ical/bin # chmod a+rwx ~/sqlitedb
(foursquare-swarm-ical) <username>@<computername>:~/venvs/foursquare-swarm-ical/bin # ./foursquare-swarm-ical --access-token <mytoken> --max-size 1M -o swarm-checkins.ical --database ~/sqlitedb/
Traceback (most recent call last):
  File "/Users/<username>/venvs/foursquare-swarm-ical/bin/./foursquare-swarm-ical", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/<username>/venvs/foursquare-swarm-ical/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<username>/venvs/foursquare-swarm-ical/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/<username>/venvs/foursquare-swarm-ical/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<username>/venvs/foursquare-swarm-ical/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<username>/venvs/foursquare-swarm-ical/lib/python3.12/site-packages/foursquare_swarm_ical/cli.py", line 78, in cli
    with db.database(database) as db_conn:
         ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/Users/<username>/venvs/foursquare-swarm-ical/lib/python3.12/site-packages/foursquare_swarm_ical/db.py", line 17, in database
    db = sqlite3.connect(filename, isolation_level=None)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file
```

**Comment by TheQL** [comment]
Ok, something weird is happening now... I re-ran the command after I deleted the folder `/Users/<username>/sqlitedb/` and it appears to be running.

The thing is, with this commandline:
`./foursquare-swarm-ical --access-token <mytoken> --max-size 1M -o swarm-checkins.ical --database /Users/<username>/sqlitedb/
`
It did not complain about the missing path or create the directory, it created the FILE `/Users/<username>/sqlitedb`

Still running by the way...

**Comment by TheQL** [comment]
Well... now I have a new error, but this is in fact a different issue. We could close this and move over....
Anyway, my current commandline, working fine:
`./foursquare-swarm-ical --access-token <mytoken> --max-size 10M -o /Users/<username>/4sq-checkins/swarm-checkins.ical --database /Users/<username>/4sq-checkins/checkins.sqlite`

I am planning to import ALL my checkins into Calendar.app, not sure if there's a size limit like the 1MB for Google Calendar. So I increased the default 1M to 2M and then to 10M, then to 100M and this is where it broke. Went down and it fails even at 20M, 15M is the highest working number I tried.

Error:
```
./foursquare-swarm-ical --access-token <mytoken> --max-size 20M -o /Users/<username>/4sq-checkins/swarm-checkins.ical --database /Users/<username>/4sq-checkins/checkins.sqlite
Traceback (most recent call last):
  File "/Users/<username>/venvs/foursquare-swarm-ical/bin/./foursquare-swarm-ical", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/<username>/venvs/foursquare-swarm-ical/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<username>/venvs/foursquare-swarm-ical/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/<username>/venvs/foursquare-swarm-ical/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<username>/venvs/foursquare-swarm-ical/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<username>/venvs/foursquare-swarm-ical/lib/python3.12/site-packages/foursquare_swarm_ical/cli.py", line 85, in cli
    output.write(ical.ical(
                 ^^^^^^^^^^
  File "/Users/<username>/venvs/foursquare-swarm-ical/lib/python3.12/site-packages/foursquare_swarm_ical/ical.py", line 20, in ical
    prefix = emojis.get_emoji_for_venue(checkin['venue']) if emojis else "@"
                                        ~~~~~~~^^^^^^^^^
KeyError: 'venue'
```

**Comment by liskin** [comment]
Still running probably means it's doing something 👍
`--verbose` would make it say what, I think

**Comment by liskin** [comment]
Right, that ValueError means the specific checkin entry is malformed or something. We'll need to tweak the error handling to attach some more debug info to be able to diagnose this

**Comment by liskin** [comment]
It's bedtime now but I'll keep this unread in my inbox and try to get back to you over the weekend

**Comment by TheQL** [comment]
> Right, that ValueError means the specific checkin entry is malformed or something. We'll need to tweak the error handling to attach some more debug info to be able to diagnose this

Understood. So it's not the size but it's just that a specific size one or more "malformed" checkins are encountered that don't export well to .ics
No hurry! I'm glad I got somewhere!

**Comment by liskin** [comment]
Yes your database very likely already has all the data, it's just the ical export that's glitching. You could use some other tool to look into it if you wish 🙂

**Comment by TheQL** [comment]
I browsed the .sqlite file and it looks fine indeed. But I guess it won't be easy to export a valid .ics file from that - you've already done all the hard work. It's probably not a huge fix once the issue is found. But now bedtime for me as well!

**Comment by TheQL** [comment]
The table has 67136 rows while the 17M .ics file has 57670 check-ins. So there are not a lot missing, but I'd still love to have them all ;)

**Comment by TheQL** [comment]
Hi @liskin, did a new import today and wondered if you've ever come around to check what could lead to the .ics export failing on specific entries. Maybe the code could just skip faulty entries, guess it's maybe even just a single one, on the other hand it might just be an encoding issue. Not sure... Would greatly appreciate an advice. Maybe I could just add a skip command myself somewhere...

**Comment by TheQL** [comment]
One more thing, I know it's not related to this tool, but just wanted to share.
Suddenly I was unable to sync calendar events on iCloud when creating them on iOS. On Mac it said I had insufficient iCloud Storage, which is crap since I have ~1.5TB of free space. But apparently limits apply: https://support.apple.com/en-us/103188
These limits don't make much sense, but after deleting my imported Swarm calendar syncing worked again. There were 61043 events in said calendar, so I guess if I create another 60k legit events, my calendar will break again and importing my Swarm calendar is out of the question anyway, at least at full size. Instead of importing 17 or 18MB I can limit that to a lot less, but it won't go very far back then.

**Comment by liskin** [comment]
> Hi [@liskin](https://github.com/liskin), did a new import today and wondered if you've ever come around to check what could lead to the .ics export failing on specific entries. Maybe the code could just skip faulty entries, guess it's maybe even just a single one, on the other hand it might just be an encoding issue. Not sure... Would greatly appreciate an advice. Maybe I could just add a skip command myself somewhere...

Hey, really sorry for the delay. Life's been busy. I just released https://github.com/liskin/foursquare-swarm-ical/releases/tag/v1.1.0 that adds `--skip-errors` plus some extra logging.

**Comment by TheQL** [comment]
Thanks a lot for this! Turns out I have 2 check-ins on my DB that can't be transformed to .ics.

I'm not even sure what those contain, apart from the date they look really empty.

```
WARNING - Failed to process checkin:
checkin={'comments': {'count': 0}, 'createdAt': 1347895794, 'id': '505741f2e4b088edb27d42cc', 'isMayor': False, 'like': False, 'likes': {'count': 0, 'groups': []}, 'photos': {'count': 0, 'items': []}, 'posts': {'count': 0, 'textCount': 0}, 'source': {'name': 'Foursquare for iOS', 'url': 'https://foursquare.com/download/#/iphone'}, 'timeZoneOffset': 120, 'type': 'checkin'}
Traceback (most recent call last):
  File "/Users/ql/.local/pipx/venvs/foursquare-swarm-ical/lib/python3.14/site-packages/foursquare_swarm_ical/ical.py", line 27, in ical
    prefix = emojis.get_emoji_for_venue(checkin['venue']) if emojis else "@"
                                        ~~~~~~~^^^^^^^^^
KeyError: 'venue'
WARNING - Failed to process checkin:
checkin={'comments': {'count': 0}, 'createdAt': 1275587711, 'id': '4c07ec7f340720a11e508293', 'isMayor': False, 'like': False, 'likes': {'count': 0, 'groups': []}, 'photos': {'count': 0, 'items': []}, 'posts': {'count': 0, 'textCount': 0}, 'timeZoneOffset': 120, 'type': 'checkin'}
Traceback (most recent call last):
  File "/Users/ql/.local/pipx/venvs/foursquare-swarm-ical/lib/python3.14/site-packages/foursquare_swarm_ical/ical.py", line 27, in ical
    prefix = emojis.get_emoji_for_venue(checkin['venue']) if emojis else "@"
                                        ~~~~~~~^^^^^^^^^
KeyError: 'venue'
```

There is no "venue" information at all on these check-ins, however that's possible! Anyway, thanks again!
